version: '3.0'

services:
  gateway:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gateway
    restart: always
    command: npm run server:gateway
    volumes:
      - .:/app
    environment:
      AUTH_SERVICE: http://localhost:9999/graphql
      CHANNEL_SERVICE: http://localhost:9999/graphql
      EMOJI_SERVICE: http://localhost:9999/graphql
      PTV_OAUTH_KEY: LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQ0lqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FnOEFNSUlDQ2dLQ0FnRUFtcThsdS9GcytyNnBGWUZnQUFrNQpPMW9CVHR4TWVvdkZiRTZDUVJ4SkdYL0tJOVpOZEhJT25HamNFY1BqTW9SOHpYUysrYkdjYTZOY1ZjK2R4RkxXCjZtaWtzc2hRanlhWWxuRm95cXcwaGJJSlFPQXBxZW5WN21Bdnh5bVRGRmxQWUFvSkIxNUYzdHNpdWNlVkF6YjkKOFpiWDNibVc1d0x0eGZqRnFCTWN1ejB4dFN3WWRqK3VSeHpjSWpGWWVTcW9STFFWUGZ3NG9JNkZMaGRMeWZHZwp3RWlqTlF4cW9FY3hDN3p5Tnk3WXpuUk5LSVVrUVpNZUtCRU55c2hBUktHdVVwa3dCRFFoUWxXeEJVRSs0UkliCmFsZFVacE5pSFJLU3MrZHM4eFJNbUQ0VzgyTnFZaXJNTDBLOU9vQVU0Wm82NEZtYjZuaWRtZDAyRzBNZk90dWUKSWhQRGt2WHpVK3Q1WmFMRk9oZDFPVTRNdThmRXlIbzkrMm1vMC9yQ0g2QzZOMmFjeFB0d1dvOEhqa0dIaUdQSQpJM2cxa3Qxa3V6d1hvcnV6b2FHMGpCUHJOMHQvbnJXdU5YbHhrb3BaUmt2YkRTMWhqaWl4RE9xMVloVlExbVpzCmFLSmRVMFM0WnJUSUJRSGRIS0lpSTVGYTh3TVNwV0tJcUF6OVdlTDA3MzhpMWtaQk1NdjRRcXpvRUZyWEhCVDYKTW5ocllyYTdTREdlTzl0OVFQOFZZLzhkb2FIM0wyRXVJS3J4SFJKbXRvMWFXSnlET2NkelltOU1KbnpUdVBrYQplbVBkMGc5dEZNN004ck1oRU9Bamx6SHptTzh1SzdPTDIvZFNoM0xBSEJqdTArMXMyTElxbEpzTkRJSWd5U3h1CmdydlVuZU1USys4VXZ1NmdXTmg3cVI4Q0F3RUFBUT09Ci0tLS0tRU5EIFBVQkxJQyBLRVktLS0tLQo=
    networks:
      - gateway
 
networks:
  gateway:
 
